### ISSUE TITLE
RestTemplate(동기) -> WebClient(동기 + 비동기)로 변경

### ISSUE THREAD

**Issue by Hchanghyeon** [Hchanghyeon/omg#32]
## 📄 설명
- RestTemplate을 이용하여 동기적으로 요청하는 API 요청 코드를 WebClient를 활용하여 동기 + 비동기로 구성한다.
- 비동기 요청시 성능 향상 기대
   - 기존: 서버로 데이터 요청시 외부 API 5개 동기 호출
   - 변경 후: 서버로 데이터 요청시 외부 API 1개 동기 + 4개 비동기 처리(사용자의 ID를 기반으로 

## ✅ 할 일 목록
- [ ] WebClient 의존성 추가 및 설정 추가
- [ ] WebClient로 구현한 API 구현체 생성 및 적용
- [ ] 기존 RestTemplate과 WebClient의 성능 차이 확인

**Comment by hanjo8813** [comment]
virtual thread + RestClient + HttpInterface 조합은 어떨까요?
(비동기 쉽게 + WebClient 편의성 + feign 같은 명시적 인터페이스)

WebClient를 사용하려고 webflux 의존성을 모두 끌고와야하는 문제때문에 RestClient가 생겼는데.. 리뷰 기억나요? ㅋㅋㅋ
https://github.com/Java-and-Script/pickple-back/pull/28#discussion_r1377460108

**Comment by Hchanghyeon** [comment]
@hanjo8813 
헉 ㅎㅎ 의견 감사합니다. 이 프로젝트 진행하면서 구현할 때는 기억 안났었는데, 저 리뷰 보니까 기억이 나네요..!
지금 WebClient 구현하는 것도 아직 WebFlux 개념을 제대로 이해못해서 그런지 WebClient로 구현해서 조금 숙달해보고 말씀하신대로 Virtual thread + RestClient + HttpInterface 조합써서 또 업그레이드 해보겠습니다ㅎㅎㅎ

👍👍👍👍 피드백 최고최고~! 👍👍
